version: '3.8'

services:
  orchestra-section:
    image: section-img
    hostname: orchestra-section
    container_name: orchestra-section
#    environment:
#      - SERVER_PORT=8002
#      - ORCHESTRA_INSTRUMENT_URL=http://orchestra-instrument:8081
    ports:
      - "8082:8082"

  orchestra-instrument:
    image: instrument-img
    hostname: orchestra-instrument
    container_name: orchestra-instrument
#    environment:
#      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  orchestra-ng:
    container_name: orchestra-ng
    image: angular-img
    ports:
      - "80:80"
    depends_on:
      - "orchestra-section"
      - "orchestra-instrument"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - ORCHESTRA_INSTRUMENT_URL=orchestra-instrument
#      - ORCHESTRA_SECTION_URL=orchestra-section:8082
      - INSTRUMENT_PORT=8081
#      - SECTION_PORT=8082