version: '3.8'

services:
  orchestra-section:
    image: section-img
    container_name: orchestra-section
    hostname: orchestra-section
    ports:
      - "8082:8082"
    depends_on:
      - "section-db"

  orchestra-instrument:
    image: instrument-img
    container_name: orchestra-instrument
    hostname: orchestra-instrument
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  orchestra-ng:
    container_name: orchestra-ng
    image: angular-img
    ports:
      - "80:80"
    depends_on:
      - "orchestra-section"
      - "orchestra-instrument"
    environment:
      - ORCHESTRA_INSTRUMENT_URL=orchestra-instrument
      - ORCHESTRA_SECTION_URL=orchestra-section
      - INSTRUMENT_PORT=8081
      - SECTION_PORT=8082
      - SERVER_PORT=80

  section-db:
    container_name: section-db
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password