version: '3.8'

services:
  orchestra-section1:
    image: section-img
    build:
      context: ./orchestra-section
    container_name: orchestra-section1
    hostname: orchestra-section1
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://orchestra-eureka:8080/eureka"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://section-db:5432/section-db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      SERVER_PORT: "8080"
    #    ports:
    #      - "8082:8082"
    depends_on:
      - "section-db"

  orchestra-section2:
    image: section-img
    build:
      context: ./orchestra-section
    container_name: orchestra-section2
    hostname: orchestra-section2
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://orchestra-eureka:8080/eureka"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://section-db:5432/section-db"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
      EUREKA_INSTANCE_INSTANCE_ID: "2"
      SERVER_PORT: "8080"
    #    ports:
    #      - "8082:8082"
    depends_on:
      - "section-db"

  orchestra-instrument-1:
    image: instrument-img
    build:
      context: ./orchestra-instrument
    container_name: orchestra-instrument1
    hostname: orchestra-instrument1
    environment:
      #      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://instrument-db:5432/instrument-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_INSTANCE_INSTANCE_ID=1
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://orchestra-eureka:8080/eureka
    #    ports:
    #      - "8081:8081"
    depends_on:
      - instrument-db

  orchestra-instrument-2:
    image: instrument-img
    build:
      context: ./orchestra-instrument
    container_name: orchestra-instrument2
    hostname: orchestra-instrument2
    environment:
      #      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://instrument-db:5432/instrument-db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_INSTANCE_INSTANCE_ID=2
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SERVER_PORT=8080
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://orchestra-eureka:8080/eureka
    #    ports:
    #      - "8081:8081"
    depends_on:
      - instrument-db

  orchestra-ng:
    container_name: orchestra-ng
    image: angular-img
    build:
      context: ./orchestra-ng
    ports:
      - "80:80"
    #    depends_on:
    #      - "orchestra-section1"
    #      - "orchestra-instrument1"
    environment:
      - ORCHESTRA_INSTRUMENT_URL=orchestra-instrument
      - ORCHESTRA_SECTION_URL=orchestra-section
      - INSTRUMENT_PORT=8080
      - SECTION_PORT=8080
      - SERVER_PORT=80
      - API_URL=http://orchestra-gateway:8080/api

  section-db:
    container_name: section-db
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=section-db
    volumes:
      - section-db-data:/var/lib/postgresql/data

  instrument-db:
    container_name: instrument-db
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=instrument-db
    volumes:
      - instrument-db-data:/var/lib/postgresql/data

  orchestra-eureka:
    image: eureka-img
    build:
      context: ./orchestra-eureka
    container_name: orchestra-eureka
    ports:
      - "8090:8080"

  orchestra-gateway:
    image: gateway-img
    build:
      context: ./orchestra-gateway
    container_name: orchestra-gateway
    hostname: orchestra-gateway
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://orchestra-eureka:8080/eureka"
      ORCHESTRA_GATEWAY_HOST: "orchestra-gateway:8080"
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  section-db-data:
  instrument-db-data: