version: '3.8'

services:
  orchestra-section:
    image: section-img
    build:
      context: ./orchestra-section
    hostname: orchestra-section
    container_name: orchestra-section
    environment:
      - SERVER_PORT=8002
      - ORCHESTRA_INSTRUMENT_URL=http://orchestra-instrument:8081
    ports:
      - "8082:8082"

  orchestra-instrument:
    image: instrument-img
    build:
      context: ./orchestra-instrument
    hostname: orchestra-instrument
    container_name: orchestra-instrument
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081:8081"

  orchestra-ng:
    container_name: orchestra-ng
    image: angular-img
    build:
      context: ./orchestra-ng
    ports:
      - "80:80"
    depends_on:
      - "orchestra-section"
      - "orchestra-instrument"
#    restart: on-failure
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - ORCHESTRA_INSTRUMENT_URL=orchestra-instrument:8081
      - ORCHESTRA_SECTION_URL=orchestra-section:8082
#      - INSTRUMENT_PORT=8081
#      - SECTION_PORT=8082
#    volumes:
#      - ./templates:/etc/nginx/templates
#    command: [" envsubst  '${ORCHESTRA_INSTRUMENT_URL}, ${ORCHESTRA_SECTION_URL}'
#      < /etc/nginx/conf.d/default.conf.template
#      > /etc/nginx/conf.d/default.conf
#      && nginx -g 'daemon off;' "]