### print all instruments - collection
GET http://localhost:8080/api/instruments

### print an instrument
GET http://localhost:8080/api/instruments/c3fe24ae-0000-0000-0000-0000c3fe24ae

### delete an instrument
DELETE http://localhost:8080/api/instruments/c3fe24ae-0000-0000-0000-0000c3fe24ae

### create an instrument
PUT http://localhost:8080/api/instruments/c3fe24ae-0000-0000-0000-0000c3fe24ae
Content-Type: application/json

{
"name": "violin",
"production_year": 1850,
"sectionId": "6ed878ec-0000-0000-0000-00006ed878ec"
}


### print all instruments from a section - collection ..... not OK
GET http://localhost:8080/api/sections/6ed878ec-0000-0000-0000-00006ed878ec/instruments


### print all sections - collection
GET http://localhost:8080/api/sections

### print a section
GET http://localhost:8080/api/sections/6ed878ec-0000-0000-0000-00006ed878ec

### delete a section
DELETE http://localhost:8080/api/sections/6ed878ec-0000-0000-0000-00006ed878ec

### create a section
PUT http://localhost:8080/api/sections/6ed878ec-0000-0000-0000-00006ed878ec
Content-Type: application/json

{
"name": "String",
"volume": 5,
  "location": 1
}