FROM node:20-alpine3.19 as build

LABEL org.opencontainers.image.title="orchestra-ng"
#LABEL org.opencontainers.image.authors="MD191684"
#LABEL org.opencontainers.image.version="1.0.0-SNAPSHOT"
#LABEL org.opencontainers.image.description="Orchestra application - Angular"

#ENV VERSION="1.0-SNAPSHOT"

# Set the working directory in the container
WORKDIR /usr/local/app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

#COPY ./ /usr/local/app/

# Install Angular CLI globally
#RUN npm install -g @angular/cli

# Install project dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Build the Angular app for production
#RUN ng build
RUN npm run build

#ENV API_URL http://localhost:8080/api

# Expose port 80 to the outside world
#EXPOSE 80

# Run the Angular app when the container launches
#CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]

# Step2: serve app with nginx server
# Use official nginx image as the base image
FROM nginx:1.23-alpine3.17
# Copy the build output to replace the default nginx contents.
# be sure to replace app-name with name of your app
COPY nginx.conf /etc/nginx/nginx.conf
COPY /nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/local/app/dist/orchestra-ng /usr/share/nginx/html

# Expose port 80
EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
