FROM nginx:1.17.0

LABEL org.opencontainers.image.title="orchestra-ng"
LABEL org.opencontainers.image.authors="MD191684"
LABEL org.opencontainers.image.version="1.0.0-SNAPSHOT"
LABEL org.opencontainers.image.description="Orchestra application - Angular"


ENV VERSION="1.0-SNAPSHOT"

ENV API_URL http://localhost:8080/api

EXPOSE 8080

#ADD dist/orchestra-ng /usr/share/nginx/html/
#ADD docker/etc/nginx/templates/ /etc/nginx/templates/
